import { StyleSheet } from 'react-native';

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 60,
    paddingHorizontal: 20,
  },
  profileImage: {
    width: 500,
    height: 740,
    marginBottom: 20,
    backgroundColor: '#ffffff',
  },
  nameHi: {
    position: 'absolute',
    left: 0,
    right: 210,
    top: 570, 
    textAlign: 'center',
    zIndex: 2,
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 4,
    fontSize: 35,
    fontWeight: 'bold',
    color: '#fff',
  },
  nameOn: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 600, 
    textAlign: 'center',
    zIndex: 2,
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 4,
    fontSize: 40,
    fontWeight: 'bold',
    color: '#fff',
  },
  name: {
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 6,
    color: '#fff',
  },
  title: {
    position: 'absolute',
    left: 0,
    right: 90,
    top: 640, 
    textAlign: 'center',
    zIndex: 2,
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 4,
    fontSize: 25,
    fontWeight: 'bold',
    color: '#fff',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '600',
    marginTop: 24,
    marginBottom: 8,
    color: '#333',
    alignSelf: 'flex-start',
  },
  sectionContent: {
    fontSize: 16,
    color: '#444',
    marginBottom: 8,
    alignSelf: 'flex-start',
  },
  skillsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 8,
    alignSelf: 'flex-start',
  },
  skill: {
    backgroundColor: '#e0e0e0',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 4,
    marginRight: 8,
    marginBottom: 8,
    fontSize: 14,
    color: '#333',
  },
  contactForm: {
    width: 300,
    marginTop: 16,
    marginBottom: 16,
    alignSelf: 'stretch',
  },
  input: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    padding: 10,
    marginBottom: 12,
    fontSize: 16,
    backgroundColor: '#fff',
    color: '#222',
  },
  messageBox: {
    height: 80,
    textAlignVertical: 'top',
  },
  submitButton: {
    backgroundColor: '#007AFF',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 100,
  },
  submitButtonDisabled: {
    backgroundColor: '#b0b0b0',
  },
  submitButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
});

export const darkStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 60,
    paddingHorizontal: 20,
  },
  profileImage: {
    width: 500,
    height: 740,
    marginBottom: 20,
  },
  nameHi: {
    position: 'absolute',
    left: 0,
    right: 210,
    top: 570, 
    textAlign: 'center',
    zIndex: 2,
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 4,
    fontSize: 35,
    fontWeight: 'bold',
    color: '#fff',
  },
  nameOn: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 600, 
    textAlign: 'center',
    zIndex: 2,
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 4,
    fontSize: 40,
    fontWeight: 'bold',
    color: '#fff',
  },
  name: {
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 6,
    color: '#fff',
  },
  title: {
    position: 'absolute',
    left: 0,
    right: 90,
    top: 640, 
    textAlign: 'center',
    zIndex: 2,
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 4,
    fontSize: 25,
    fontWeight: 'bold',
    color: '#fff',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '600',
    marginTop: 24,
    marginBottom: 8,
    color: '#fff',
    alignSelf: 'flex-start',
  },
  sectionContent: {
    fontSize: 16,
    color: '#fff',
    marginBottom: 8,
    alignSelf: 'flex-start',
  },
  skillsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 8,
    alignSelf: 'flex-start',
  },
  skill: {
    backgroundColor: '#333',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 4,
    marginRight: 8,
    marginBottom: 8,
    fontSize: 14,
    color: '#fff',
  },
  contactForm: {
    width: 300,
    marginTop: 16,
    marginBottom: 16,
    alignSelf: 'stretch',
  },
  input: {
    borderWidth: 1,
    borderColor: '#444',
    borderRadius: 8,
    padding: 10,
    marginBottom: 12,
    fontSize: 16,
    backgroundColor: '#222',
    color: '#fff',
  },
  messageBox: {
    height: 200,
    textAlignVertical: 'top',
  },
  submitButton: {
    backgroundColor: '#007AFF',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 100,
  },
  submitButtonDisabled: {
    backgroundColor: '#444',
  },
  submitButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
  },
});
